### PR TITLE
fix example code in readme

### LINKED ISSUE #2: Example from README fails to run
The example usage found in [README.rst#usage-example](https://github.com/adafruit/Adafruit_CircuitPython_ADS7830/blob/main/README.rst#usage-example) fails to run with the following error:

```
code.py output:
Traceback (most recent call last):
  File "code.py", line 8, in <module>
AttributeError: 'module' object has no attribute 'Adafruit_ADS7830'
```

After some research and experimentation, I arrived at this resolution:

```py
import time
import board
import adafruit_ads7830.ads7830
from adafruit_ads7830.analog_in import AnalogIn

i2c = board.I2C()

# Initialize ADS7830
adc = adafruit_ads7830.ads7830.ADS7830(i2c)
analog_inputs = []
for i in range(8):
    c = AnalogIn(adc, i)
    analog_inputs.append(c)

while True:
    for i in range(8):    
        print(f"ADC input {i} = {analog_inputs[i].value}")
    time.sleep(0.1)
```

As a diff, if it helps:

```diff
@@ -1,17 +1,18 @@
 import time
 import board
-import adafruit_ads7830
+import adafruit_ads7830.ads7830
+from adafruit_ads7830.analog_in import AnalogIn

 i2c = board.I2C()

 # Initialize ADS7830
-adc = adafruit_ads7830.Adafruit_ADS7830(i2c)
+adc = adafruit_ads7830.ads7830.ADS7830(i2c)
 analog_inputs = []
 for i in range(8):
-    c = adc.inputs[i]
+    c = AnalogIn(adc, i)
     analog_inputs.append(c)

 while True:
-    for i in enumerate(analog_inputs):
+    for i in range(8):
         print(f"ADC input {i} = {analog_inputs[i].value}")
     time.sleep(0.1)
```

### PR DESCRIPTION
**Pull request by FoamyGuy**
@ladyada 
Resolves: #2

### CODE REVIEW

**Review by ladyada — APPROVED** [review]
did you test this?

**Comment by FoamyGuy** [comment]
@ladyada No, I don't have the hardware. 

It's just taken from the issue comment.

**Comment by ladyada** [comment]
ok all PRs should be tested before we can merge, folks are often wrong, dont trust internet strangers :)

**Comment by FoamyGuy** [comment]
I've now tested on a QTPY s3. Confirmed the existing code in Readme raises the exception noted and the new version runs and behaves correctly.

**Comment by ladyada** [comment]
yay

**Pull request merged**
